/** Self-contained recovery styling: no editable assets or external requests. */
export const chirpMark = `<svg width="28" height="28" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M3 4h13v4h5v4h-8v9H8V11H3z"/><path fill="#161b1d" d="M12 6h2v2h-2z"/></svg>`;

export const authStyles = `
*{box-sizing:border-box}body{margin:0;background:#161b1d;color:#eeeee7;font:16px/1.65 system-ui,sans-serif;-webkit-font-smoothing:antialiased}
.auth-shell{max-width:32rem;margin:10vh auto;padding:1.5rem}.onboarding{max-width:66rem;margin:0 auto;padding:3rem 2rem 5rem}
.brand{display:inline-flex;align-items:center;gap:.6rem;font-size:1.6rem;font-weight:650;letter-spacing:-.06em;text-decoration:none;color:#eeeee7}.brand svg{color:#e69b83}.brand span{color:#b8d7c3;margin-left:-.55rem}
h1,h2,p{margin-top:0}h1{font:normal clamp(2.7rem,6vw,4.5rem)/1.1 Georgia,serif;letter-spacing:-.04em;margin:2.8rem 0 1.1rem}h1 em{color:#b8d7c3;font-weight:normal}h2{font-size:1.15rem;font-weight:550;line-height:1.4;margin-bottom:.6rem}p{color:#a8b4b4}.intro{max-width:35rem;font-size:1.1rem;margin-bottom:3rem}
.steps{list-style:none;padding:0;margin:0;border-top:1px solid #354140}.step{display:grid;grid-template-columns:3rem 1fr;gap:1rem;padding:2rem 0;border-bottom:1px solid #354140}.step-number{font:13px/2 monospace;color:#c9bfdf}.step-body{max-width:38rem}.step p{margin-bottom:1rem}.step p:last-child{margin-bottom:0}.pending{opacity:.55}
label,input,button{display:block}label{font-size:.85rem;color:#bcc8c6}input,button,.button{font:inherit;padding:.75rem 1rem;box-sizing:border-box;border-radius:4px}input{width:100%;margin:.5rem 0 1rem;border:1px solid #52625e;background:#1e2728;color:#eeeee7;letter-spacing:.12em}button,.button{border:0;background:#b8d7c3;color:#17201d;cursor:pointer;text-decoration:none;font-weight:550;display:inline-flex;align-items:center;justify-content:center}button:disabled{opacity:.5;cursor:wait}a{color:#b8d7c3}a:hover{color:#d5ecde}button:hover,.button:hover{background:#c9e3d2;color:#17201d}button:focus-visible,a:focus-visible,input:focus-visible,pre:focus-visible{outline:2px solid #c9bfdf;outline-offset:4px}
code,pre{font:13px/1.7 ui-monospace,monospace}code{color:#c9bfdf}pre{white-space:pre-wrap;overflow-wrap:anywhere;padding:1rem;border:1px solid #354140;background:#1c2425;color:#cbd4cf}.actions{display:flex;align-items:center;gap:1.5rem;flex-wrap:wrap;margin-top:1.4rem}.footnote{font-size:.85rem;margin-top:1.8rem}#status{min-height:1.6em;color:#c9bfdf;margin-top:1rem}.auth-shell form button{width:100%}
@media(max-width:600px){.onboarding{padding:1.5rem 1.2rem 3rem}.auth-shell{margin:4vh auto}.step{grid-template-columns:1.7rem 1fr;gap:.6rem;padding:1.6rem 0}h1{margin-top:2rem}.intro{margin-bottom:2rem}}
`;
