import { tableShape, type ColumnShape } from "@comms/storage/remote-migrations";
import type { SqlClient } from "effect/unstable/sql/SqlClient";

type Engine = "pg" | "mysql";
type Pair<A> = readonly [A, A];
interface Column {
	readonly name: string;
	readonly kind: "integer" | "blob" | "text" | number;
	readonly nullable: boolean;
	readonly identity?: boolean;
	readonly defaults?: Pair<string>;
	readonly suffix?: Pair<string>;
	readonly expressions?: Pair<string | null>;
}

/** Boot's columns are declared once; only SQL syntax and catalog spelling vary by engine. */
export const column = (
	name: string,
	kind: Column["kind"],
	nullable: boolean,
	options: Omit<Column, "name" | "kind" | "nullable"> = {},
): Column => ({ name, kind, nullable, ...options });

/** Uses the app's shared shape checker and migration executor, with no SQL parsing or schema discovery. */
export const bootTable = (
	sql: SqlClient,
	engine: Engine,
	step: number,
	name: string,
	columns: readonly Column[],
	primary: readonly string[],
	constraints: Pair<string>,
	options: Pair<Parameters<typeof tableShape>[4]>,
	unique: readonly { readonly name: string; readonly columns: readonly string[] }[],
) => {
	const index = engine === "pg" ? 0 : 1;
	const quote = (value: string) => (engine === "pg" ? `"${value}"` : `\`${value}\``);
	const shapes: readonly ColumnShape[] = columns.map((column) => ({
		name: column.name,
		type:
			column.kind === "integer"
				? "bigint"
				: column.kind === "blob"
					? engine === "pg"
						? "bytea"
						: "longblob"
					: engine === "pg"
						? "text"
						: typeof column.kind === "number"
							? "varchar"
							: "longtext",
		...(engine === "mysql" && typeof column.kind === "number" ? { length: column.kind } : {}),
		nullable: column.nullable,
		default: column.defaults?.[index] ?? null,
		identity: column.identity ?? false,
		identityGeneration: column.identity ? (engine === "pg" ? "BY DEFAULT" : "AUTO_INCREMENT") : null,
		expression: column.expressions?.[index] ?? (engine === "pg" ? null : ""),
		collation:
			engine === "mysql" && (column.kind === "text" || typeof column.kind === "number") ? "utf8mb4_0900_bin" : null,
	}));
	const definitions = columns.map((column) => {
		const type =
			column.kind === "integer"
				? "bigint"
				: column.kind === "blob"
					? engine === "pg"
						? "bytea"
						: "longblob"
					: engine === "pg"
						? "text"
						: `${typeof column.kind === "number" ? `varchar(${column.kind})` : "longtext"} CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin`;
		const identity = column.identity ? (engine === "pg" ? " GENERATED BY DEFAULT AS IDENTITY" : " AUTO_INCREMENT") : "";
		return `${quote(column.name)} ${type}${identity}${column.nullable ? "" : " NOT NULL"}${column.suffix?.[index] ?? ""}`;
	});
	return {
		step,
		name,
		unique,
		run: sql.unsafe(
			`CREATE TABLE ${quote(name)} (\n${definitions.join(",\n")},\n${constraints[index]}\n)${engine === "mysql" ? " ENGINE=InnoDB" : ""}`,
		),
		postcondition: tableShape(sql, name, shapes, primary, options[index]),
	};
};

/** Unbounded boot identifiers retain the existing collision-refusing unique hash index. */
export const hashColumn = (name: string) =>
	column(`${name}_hash`, 64, true, {
		suffix: [
			` GENERATED ALWAYS AS (encode(sha256(decode(replace("${name}",chr(92),chr(92)||chr(92)),'escape')),'hex')) STORED`,
			` GENERATED ALWAYS AS (SHA2(\`${name}\`,256)) STORED`,
		],
		expressions: [
			`encode(sha256(decode(replace(${name}, chr(92), (chr(92) || chr(92))), 'escape'::text)), 'hex'::text)`,
			`sha2(\`${name}\`,256)`,
		],
	});

export const eventColumn = (name: "type" | "actor" | "instance" | "level") =>
	column(name, "text", true, {
		suffix: [
			` GENERATED ALWAYS AS (("event"::jsonb ->> '${name}')) STORED`,
			` GENERATED ALWAYS AS (CASE WHEN JSON_TYPE(JSON_EXTRACT(\`event\`,'$.${name}'))='NULL' THEN NULL ELSE JSON_UNQUOTE(JSON_EXTRACT(\`event\`,'$.${name}')) END) STORED`,
		],
		expressions: [
			`((event)::jsonb ->> '${name}'::text)`,
			`(case when (json_type(json_extract(\`event\`,_utf8mb4\\'$.${name}\\')) = _utf8mb4\\'NULL\\') then NULL else json_unquote(json_extract(\`event\`,_utf8mb4\\'$.${name}\\')) end)`,
		],
	});
