import { tableShape } from "@comms/storage/remote-migrations";
import type { SqlClient } from "effect/unstable/sql/SqlClient";

/** Explicit fresh remote schema; existing SQLite histories use boot-schema.ts. */
export const remoteBootRuntime = (sql: SqlClient, engine: "pg" | "mysql") =>
	[
		{
			step: 1,
			name: "generations",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "generations" (\n"n" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n"snapshot_dir" text,\n"entry_file" text NOT NULL,\n"status" text NOT NULL CHECK ("status" IN (\'starting\',\'live\',\'failed\',\'retired\')),\n"good" bigint NOT NULL DEFAULT 0 CHECK ("good" IN (0,1)),\n"stderr" text NOT NULL DEFAULT \'\',\n"error" text,\n"started_at" bigint NOT NULL,\n"healthy_at" bigint,\n"retired_at" bigint,\n"backup_id" text,\nPRIMARY KEY ("n")\n)'
					: "CREATE TABLE `generations` (\n`n` bigint AUTO_INCREMENT NOT NULL,\n`snapshot_dir` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`entry_file` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL CHECK (`status` IN ('starting','live','failed','retired')),\n`good` bigint NOT NULL DEFAULT 0 CHECK (`good` IN (0,1)),\n`stderr` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL DEFAULT (''),\n`error` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`started_at` bigint NOT NULL,\n`healthy_at` bigint,\n`retired_at` bigint,\n`backup_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\nPRIMARY KEY (`n`)\n)",
			),
			postcondition: tableShape(
				sql,
				"generations",
				engine === "pg"
					? [
							{ name: "n", type: "bigint", nullable: false },
							{ name: "snapshot_dir", type: "text", nullable: true },
							{ name: "entry_file", type: "text", nullable: false },
							{ name: "status", type: "text", nullable: false },
							{ name: "good", type: "bigint", nullable: false },
							{ name: "stderr", type: "text", nullable: false },
							{ name: "error", type: "text", nullable: true },
							{ name: "started_at", type: "bigint", nullable: false },
							{ name: "healthy_at", type: "bigint", nullable: true },
							{ name: "retired_at", type: "bigint", nullable: true },
							{ name: "backup_id", type: "text", nullable: true },
						]
					: [
							{ name: "n", type: "bigint", nullable: false },
							{ name: "snapshot_dir", type: "longtext", nullable: true },
							{ name: "entry_file", type: "longtext", nullable: false },
							{ name: "status", type: "varchar", nullable: false, length: 16 },
							{ name: "good", type: "bigint", nullable: false },
							{ name: "stderr", type: "longtext", nullable: false },
							{ name: "error", type: "longtext", nullable: true },
							{ name: "started_at", type: "bigint", nullable: false },
							{ name: "healthy_at", type: "bigint", nullable: true },
							{ name: "retired_at", type: "bigint", nullable: true },
							{ name: "backup_id", type: "varchar", nullable: true, length: 128 },
						],
				["n"],
			),
		},
		{
			step: 2,
			name: "settings",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "settings" (\n"key" text NOT NULL,\n"value" text NOT NULL,\nPRIMARY KEY ("key")\n)'
					: "CREATE TABLE `settings` (\n`key` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\nPRIMARY KEY (`key`)\n)",
			),
			postcondition: tableShape(
				sql,
				"settings",
				engine === "pg"
					? [
							{ name: "key", type: "text", nullable: false },
							{ name: "value", type: "text", nullable: false },
						]
					: [
							{ name: "key", type: "varchar", nullable: false, length: 128 },
							{ name: "value", type: "longtext", nullable: false },
						],
				["key"],
			),
		},
		{
			step: 6,
			name: "seq",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "seq" (\n"singleton" bigint NOT NULL CHECK ("singleton"=1),\n"next" bigint NOT NULL,\n"published_through" bigint NOT NULL,\n"pending_id" text,\n"pending_attempt" text,\n"pending_from" bigint,\n"pending_to" bigint,\nPRIMARY KEY ("singleton")\n)'
					: "CREATE TABLE `seq` (\n`singleton` bigint NOT NULL CHECK (`singleton`=1),\n`next` bigint NOT NULL,\n`published_through` bigint NOT NULL,\n`pending_id` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`pending_attempt` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`pending_from` bigint,\n`pending_to` bigint,\nPRIMARY KEY (`singleton`)\n)",
			),
			postcondition: tableShape(
				sql,
				"seq",
				engine === "pg"
					? [
							{ name: "singleton", type: "bigint", nullable: false },
							{ name: "next", type: "bigint", nullable: false },
							{ name: "published_through", type: "bigint", nullable: false },
							{ name: "pending_id", type: "text", nullable: true },
							{ name: "pending_attempt", type: "text", nullable: true },
							{ name: "pending_from", type: "bigint", nullable: true },
							{ name: "pending_to", type: "bigint", nullable: true },
						]
					: [
							{ name: "singleton", type: "bigint", nullable: false },
							{ name: "next", type: "bigint", nullable: false },
							{ name: "published_through", type: "bigint", nullable: false },
							{ name: "pending_id", type: "longtext", nullable: true },
							{ name: "pending_attempt", type: "varchar", nullable: true, length: 128 },
							{ name: "pending_from", type: "bigint", nullable: true },
							{ name: "pending_to", type: "bigint", nullable: true },
						],
				["singleton"],
			),
		},
		{
			step: 6,
			name: "events",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "events" (\n"seq" bigint NOT NULL,\n"transaction_id" text,\n"event" text NOT NULL,\n"topic" text,\n"type" text GENERATED ALWAYS AS (("event"::jsonb ->> \'type\')) STORED,\n"actor" text GENERATED ALWAYS AS (("event"::jsonb ->> \'actor\')) STORED,\n"instance" text GENERATED ALWAYS AS (("event"::jsonb ->> \'instance\')) STORED,\n"level" text GENERATED ALWAYS AS (("event"::jsonb ->> \'level\')) STORED,\nPRIMARY KEY ("seq")\n)'
					: "CREATE TABLE `events` (\n`seq` bigint NOT NULL,\n`transaction_id` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`event` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`topic` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`type` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin GENERATED ALWAYS AS (CASE WHEN JSON_TYPE(JSON_EXTRACT(`event`,'$.type'))='NULL' THEN NULL ELSE JSON_UNQUOTE(JSON_EXTRACT(`event`,'$.type')) END) STORED,\n`actor` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin GENERATED ALWAYS AS (CASE WHEN JSON_TYPE(JSON_EXTRACT(`event`,'$.actor'))='NULL' THEN NULL ELSE JSON_UNQUOTE(JSON_EXTRACT(`event`,'$.actor')) END) STORED,\n`instance` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin GENERATED ALWAYS AS (CASE WHEN JSON_TYPE(JSON_EXTRACT(`event`,'$.instance'))='NULL' THEN NULL ELSE JSON_UNQUOTE(JSON_EXTRACT(`event`,'$.instance')) END) STORED,\n`level` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin GENERATED ALWAYS AS (CASE WHEN JSON_TYPE(JSON_EXTRACT(`event`,'$.level'))='NULL' THEN NULL ELSE JSON_UNQUOTE(JSON_EXTRACT(`event`,'$.level')) END) STORED,\nPRIMARY KEY (`seq`)\n)",
			),
			postcondition: tableShape(
				sql,
				"events",
				engine === "pg"
					? [
							{ name: "seq", type: "bigint", nullable: false },
							{ name: "transaction_id", type: "text", nullable: true },
							{ name: "event", type: "text", nullable: false },
							{ name: "topic", type: "text", nullable: true },
							{ name: "type", type: "text", nullable: true, expression: "(\"event\"::jsonb ->> 'type')" },
							{ name: "actor", type: "text", nullable: true, expression: "(\"event\"::jsonb ->> 'actor')" },
							{ name: "instance", type: "text", nullable: true, expression: "(\"event\"::jsonb ->> 'instance')" },
							{ name: "level", type: "text", nullable: true, expression: "(\"event\"::jsonb ->> 'level')" },
						]
					: [
							{ name: "seq", type: "bigint", nullable: false },
							{ name: "transaction_id", type: "longtext", nullable: true },
							{ name: "event", type: "longtext", nullable: false },
							{ name: "topic", type: "longtext", nullable: true },
							{
								name: "type",
								type: "longtext",
								nullable: true,
								expression:
									"CASE WHEN JSON_TYPE(JSON_EXTRACT(`event`,'$.type'))='NULL' THEN NULL ELSE JSON_UNQUOTE(JSON_EXTRACT(`event`,'$.type')) END",
							},
							{
								name: "actor",
								type: "longtext",
								nullable: true,
								expression:
									"CASE WHEN JSON_TYPE(JSON_EXTRACT(`event`,'$.actor'))='NULL' THEN NULL ELSE JSON_UNQUOTE(JSON_EXTRACT(`event`,'$.actor')) END",
							},
							{
								name: "instance",
								type: "longtext",
								nullable: true,
								expression:
									"CASE WHEN JSON_TYPE(JSON_EXTRACT(`event`,'$.instance'))='NULL' THEN NULL ELSE JSON_UNQUOTE(JSON_EXTRACT(`event`,'$.instance')) END",
							},
							{
								name: "level",
								type: "longtext",
								nullable: true,
								expression:
									"CASE WHEN JSON_TYPE(JSON_EXTRACT(`event`,'$.level'))='NULL' THEN NULL ELSE JSON_UNQUOTE(JSON_EXTRACT(`event`,'$.level')) END",
							},
						],
				["seq"],
			),
		},
		{
			step: 6,
			name: "event_batches",
			unique: [{ name: "event_batches_id_hash_unique", columns: ["id_hash"] }],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "event_batches" (\n"row_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n"id" text NOT NULL,\n"attempt" text NOT NULL,\n"from_seq" bigint NOT NULL,\n"to_seq" bigint NOT NULL,\n"state" text NOT NULL,\n"id_hash" text GENERATED ALWAYS AS (encode(sha256(decode(replace("id",chr(92),chr(92)||chr(92)),\'escape\')),\'hex\')) STORED,\nPRIMARY KEY ("row_id")\n)'
					: "CREATE TABLE `event_batches` (\n`row_id` bigint AUTO_INCREMENT NOT NULL,\n`id` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`attempt` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`from_seq` bigint NOT NULL,\n`to_seq` bigint NOT NULL,\n`state` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`id_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin GENERATED ALWAYS AS (SHA2(`id`,256)) STORED,\nPRIMARY KEY (`row_id`)\n)",
			),
			postcondition: tableShape(
				sql,
				"event_batches",
				engine === "pg"
					? [
							{ name: "row_id", type: "bigint", nullable: false },
							{ name: "id", type: "text", nullable: false },
							{ name: "attempt", type: "text", nullable: false },
							{ name: "from_seq", type: "bigint", nullable: false },
							{ name: "to_seq", type: "bigint", nullable: false },
							{ name: "state", type: "text", nullable: false },
							{
								name: "id_hash",
								type: "text",
								nullable: true,
								expression: "encode(sha256(decode(replace(\"id\",chr(92),chr(92)||chr(92)),'escape')),'hex')",
							},
						]
					: [
							{ name: "row_id", type: "bigint", nullable: false },
							{ name: "id", type: "longtext", nullable: false },
							{ name: "attempt", type: "varchar", nullable: false, length: 128 },
							{ name: "from_seq", type: "bigint", nullable: false },
							{ name: "to_seq", type: "bigint", nullable: false },
							{ name: "state", type: "varchar", nullable: false, length: 128 },
							{ name: "id_hash", type: "varchar", nullable: true, length: 64, expression: "SHA2(`id`,256)" },
						],
				["row_id"],
			),
		},
		{
			step: 9,
			name: "child_attempts",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "child_attempts" (\n"id" text NOT NULL,\n"generation" bigint NOT NULL,\n"receipt" text NOT NULL,\n"opened" bigint NOT NULL DEFAULT 0,\n"closed" bigint NOT NULL DEFAULT 0,\n"boot_id" text,\nPRIMARY KEY ("id")\n)'
					: "CREATE TABLE `child_attempts` (\n`id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`generation` bigint NOT NULL,\n`receipt` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`opened` bigint NOT NULL DEFAULT 0,\n`closed` bigint NOT NULL DEFAULT 0,\n`boot_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\nPRIMARY KEY (`id`)\n)",
			),
			postcondition: tableShape(
				sql,
				"child_attempts",
				engine === "pg"
					? [
							{ name: "id", type: "text", nullable: false },
							{ name: "generation", type: "bigint", nullable: false },
							{ name: "receipt", type: "text", nullable: false },
							{ name: "opened", type: "bigint", nullable: false },
							{ name: "closed", type: "bigint", nullable: false },
							{ name: "boot_id", type: "text", nullable: true },
						]
					: [
							{ name: "id", type: "varchar", nullable: false, length: 128 },
							{ name: "generation", type: "bigint", nullable: false },
							{ name: "receipt", type: "longtext", nullable: false },
							{ name: "opened", type: "bigint", nullable: false },
							{ name: "closed", type: "bigint", nullable: false },
							{ name: "boot_id", type: "varchar", nullable: true, length: 128 },
						],
				["id"],
			),
		},
		{
			step: 9,
			name: "backups",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "backups" (\n"id" text NOT NULL,\n"path" text NOT NULL,\n"reason" text NOT NULL,\n"bytes" bigint NOT NULL,\n"taken_at" bigint NOT NULL,\n"published_through" bigint,\n"generation" bigint,\n"legacy_store_id" text,\n"engine" text NOT NULL CHECK ("engine" IN (\'sqlite\',\'pg\',\'mysql\')),\nPRIMARY KEY ("id")\n)'
					: "CREATE TABLE `backups` (\n`id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`path` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`reason` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`bytes` bigint NOT NULL,\n`taken_at` bigint NOT NULL,\n`published_through` bigint,\n`generation` bigint,\n`legacy_store_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`engine` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL CHECK (`engine` IN ('sqlite','pg','mysql')),\nPRIMARY KEY (`id`)\n)",
			),
			postcondition: tableShape(
				sql,
				"backups",
				engine === "pg"
					? [
							{ name: "id", type: "text", nullable: false },
							{ name: "path", type: "text", nullable: false },
							{ name: "reason", type: "text", nullable: false },
							{ name: "bytes", type: "bigint", nullable: false },
							{ name: "taken_at", type: "bigint", nullable: false },
							{ name: "published_through", type: "bigint", nullable: true },
							{ name: "generation", type: "bigint", nullable: true },
							{ name: "legacy_store_id", type: "text", nullable: true },
							{ name: "engine", type: "text", nullable: false },
						]
					: [
							{ name: "id", type: "varchar", nullable: false, length: 128 },
							{ name: "path", type: "longtext", nullable: false },
							{ name: "reason", type: "longtext", nullable: false },
							{ name: "bytes", type: "bigint", nullable: false },
							{ name: "taken_at", type: "bigint", nullable: false },
							{ name: "published_through", type: "bigint", nullable: true },
							{ name: "generation", type: "bigint", nullable: true },
							{ name: "legacy_store_id", type: "varchar", nullable: true, length: 128 },
							{ name: "engine", type: "varchar", nullable: false, length: 16 },
						],
				["id"],
			),
		},
		{
			step: 9,
			name: "cutover",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "cutover" (\n"singleton" bigint NOT NULL CHECK ("singleton"=1),\n"candidate" bigint NOT NULL,\n"prior" bigint,\n"backup" text,\n"lock_id" text NOT NULL,\n"family" text NOT NULL,\n"phase" text NOT NULL,\n"candidate_epoch" text,\nPRIMARY KEY ("singleton")\n)'
					: "CREATE TABLE `cutover` (\n`singleton` bigint NOT NULL CHECK (`singleton`=1),\n`candidate` bigint NOT NULL,\n`prior` bigint,\n`backup` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`lock_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`family` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`phase` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`candidate_epoch` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\nPRIMARY KEY (`singleton`)\n)",
			),
			postcondition: tableShape(
				sql,
				"cutover",
				engine === "pg"
					? [
							{ name: "singleton", type: "bigint", nullable: false },
							{ name: "candidate", type: "bigint", nullable: false },
							{ name: "prior", type: "bigint", nullable: true },
							{ name: "backup", type: "text", nullable: true },
							{ name: "lock_id", type: "text", nullable: false },
							{ name: "family", type: "text", nullable: false },
							{ name: "phase", type: "text", nullable: false },
							{ name: "candidate_epoch", type: "text", nullable: true },
						]
					: [
							{ name: "singleton", type: "bigint", nullable: false },
							{ name: "candidate", type: "bigint", nullable: false },
							{ name: "prior", type: "bigint", nullable: true },
							{ name: "backup", type: "varchar", nullable: true, length: 128 },
							{ name: "lock_id", type: "varchar", nullable: false, length: 128 },
							{ name: "family", type: "varchar", nullable: false, length: 128 },
							{ name: "phase", type: "varchar", nullable: false, length: 128 },
							{ name: "candidate_epoch", type: "varchar", nullable: true, length: 128 },
						],
				["singleton"],
			),
		},
		{
			step: 13,
			name: "db_restore_requests",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "db_restore_requests" (\n"proof_id" text NOT NULL,\n"proof_hash" text NOT NULL,\n"session_id" text NOT NULL,\n"idempotency_key" text,\n"backup" text NOT NULL,\n"phase" text NOT NULL CHECK ("phase" IN (\'authorized\',\'restoring\',\'working\',\'rollback\',\'restored\',\'failed\')),\n"safety_backup" text,\n"generation" bigint,\n"restored_to_seq" bigint NOT NULL,\n"event_seq" bigint,\n"failure" text,\n"lock_id" text,\n"lock_family" text,\n"lock_owned" bigint NOT NULL DEFAULT 0 CHECK ("lock_owned" IN (0,1)),\n"candidate_epoch" text,\n"source_generation" bigint,\n"prior_generation" bigint,\n"source_batch" text,\n"active_guard" bigint GENERATED ALWAYS AS (CASE WHEN "phase" IN (\'authorized\',\'restoring\',\'working\',\'rollback\') THEN 1 ELSE NULL END) STORED,\nPRIMARY KEY ("proof_id")\n)'
					: "CREATE TABLE `db_restore_requests` (\n`proof_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`proof_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`session_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`idempotency_key` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`backup` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`phase` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL CHECK (`phase` IN ('authorized','restoring','working','rollback','restored','failed')),\n`safety_backup` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`generation` bigint,\n`restored_to_seq` bigint NOT NULL,\n`event_seq` bigint,\n`failure` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`lock_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`lock_family` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`lock_owned` bigint NOT NULL DEFAULT 0 CHECK (`lock_owned` IN (0,1)),\n`candidate_epoch` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`source_generation` bigint,\n`prior_generation` bigint,\n`source_batch` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`active_guard` bigint GENERATED ALWAYS AS (CASE WHEN `phase` IN ('authorized','restoring','working','rollback') THEN 1 ELSE NULL END) STORED,\nPRIMARY KEY (`proof_id`)\n)",
			),
			postcondition: tableShape(
				sql,
				"db_restore_requests",
				engine === "pg"
					? [
							{ name: "proof_id", type: "text", nullable: false },
							{ name: "proof_hash", type: "text", nullable: false },
							{ name: "session_id", type: "text", nullable: false },
							{ name: "idempotency_key", type: "text", nullable: true },
							{ name: "backup", type: "text", nullable: false },
							{ name: "phase", type: "text", nullable: false },
							{ name: "safety_backup", type: "text", nullable: true },
							{ name: "generation", type: "bigint", nullable: true },
							{ name: "restored_to_seq", type: "bigint", nullable: false },
							{ name: "event_seq", type: "bigint", nullable: true },
							{ name: "failure", type: "text", nullable: true },
							{ name: "lock_id", type: "text", nullable: true },
							{ name: "lock_family", type: "text", nullable: true },
							{ name: "lock_owned", type: "bigint", nullable: false },
							{ name: "candidate_epoch", type: "text", nullable: true },
							{ name: "source_generation", type: "bigint", nullable: true },
							{ name: "prior_generation", type: "bigint", nullable: true },
							{ name: "source_batch", type: "text", nullable: true },
							{
								name: "active_guard",
								type: "bigint",
								nullable: true,
								expression:
									"CASE WHEN \"phase\" IN ('authorized','restoring','working','rollback') THEN 1 ELSE NULL END",
							},
						]
					: [
							{ name: "proof_id", type: "varchar", nullable: false, length: 128 },
							{ name: "proof_hash", type: "varchar", nullable: false, length: 64 },
							{ name: "session_id", type: "varchar", nullable: false, length: 128 },
							{ name: "idempotency_key", type: "varchar", nullable: true, length: 200 },
							{ name: "backup", type: "varchar", nullable: false, length: 128 },
							{ name: "phase", type: "varchar", nullable: false, length: 16 },
							{ name: "safety_backup", type: "varchar", nullable: true, length: 128 },
							{ name: "generation", type: "bigint", nullable: true },
							{ name: "restored_to_seq", type: "bigint", nullable: false },
							{ name: "event_seq", type: "bigint", nullable: true },
							{ name: "failure", type: "longtext", nullable: true },
							{ name: "lock_id", type: "varchar", nullable: true, length: 128 },
							{ name: "lock_family", type: "varchar", nullable: true, length: 128 },
							{ name: "lock_owned", type: "bigint", nullable: false },
							{ name: "candidate_epoch", type: "varchar", nullable: true, length: 128 },
							{ name: "source_generation", type: "bigint", nullable: true },
							{ name: "prior_generation", type: "bigint", nullable: true },
							{ name: "source_batch", type: "varchar", nullable: true, length: 128 },
							{
								name: "active_guard",
								type: "bigint",
								nullable: true,
								expression: "CASE WHEN `phase` IN ('authorized','restoring','working','rollback') THEN 1 ELSE NULL END",
							},
						],
				["proof_id"],
			),
		},
		{
			step: 14,
			name: "public_paths",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "public_paths" (\n"path" text NOT NULL,\nPRIMARY KEY ("path")\n)'
					: "CREATE TABLE `public_paths` (\n`path` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\nPRIMARY KEY (`path`)\n)",
			),
			postcondition: tableShape(
				sql,
				"public_paths",
				engine === "pg"
					? [{ name: "path", type: "text", nullable: false }]
					: [{ name: "path", type: "varchar", nullable: false, length: 200 }],
				["path"],
			),
		},
	] as const;
