import { bootTableShape } from "./remote-boot-schema-shape.ts";
import type { SqlClient } from "effect/unstable/sql/SqlClient";

/** Explicit fresh remote schema; existing SQLite histories use boot-schema.ts. */
export const remoteBootAuth = (sql: SqlClient, engine: "pg" | "mysql") =>
	[
		{
			step: 4,
			name: "passkeys",
			unique: [{ name: "passkeys_id_hash_unique", columns: ["id_hash"] }],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "passkeys" (\n"row_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n"id" text NOT NULL,\n"public_key" text NOT NULL,\n"counter" bigint NOT NULL,\n"transports" text NOT NULL,\n"label" text NOT NULL,\n"created_at" bigint NOT NULL,\n"id_hash" text GENERATED ALWAYS AS (encode(sha256(decode(replace("id",chr(92),chr(92)||chr(92)),\'escape\')),\'hex\')) STORED,\nPRIMARY KEY ("row_id")\n)'
					: "CREATE TABLE `passkeys` (\n`row_id` bigint AUTO_INCREMENT NOT NULL,\n`id` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`public_key` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`counter` bigint NOT NULL,\n`transports` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`label` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`created_at` bigint NOT NULL,\n`id_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin GENERATED ALWAYS AS (SHA2(`id`,256)) STORED,\nPRIMARY KEY (`row_id`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"passkeys",
				engine === "pg"
					? [
							{ name: "row_id", type: "bigint", nullable: false, identity: true },
							{ name: "id", type: "text", nullable: false },
							{ name: "public_key", type: "text", nullable: false },
							{ name: "counter", type: "bigint", nullable: false },
							{ name: "transports", type: "text", nullable: false },
							{ name: "label", type: "text", nullable: false },
							{ name: "created_at", type: "bigint", nullable: false },
							{
								name: "id_hash",
								type: "text",
								nullable: true,
								expression:
									"encode(sha256(decode(replace(id, chr(92), (chr(92) || chr(92))), 'escape'::text)), 'hex'::text)",
							},
						]
					: [
							{ name: "row_id", type: "bigint", nullable: false, identity: true },
							{ name: "id", type: "longtext", nullable: false },
							{ name: "public_key", type: "longtext", nullable: false },
							{ name: "counter", type: "bigint", nullable: false },
							{ name: "transports", type: "longtext", nullable: false },
							{ name: "label", type: "longtext", nullable: false },
							{ name: "created_at", type: "bigint", nullable: false },
							{ name: "id_hash", type: "varchar", nullable: true, length: 64, expression: "sha2(`id`,256)" },
						],
				["row_id"],
				{ foreignKeys: [], checks: engine === "pg" ? [] : [] },
			),
		},
		{
			step: 4,
			name: "auth_challenges",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "auth_challenges" (\n"id" text NOT NULL,\n"challenge" text NOT NULL,\n"ceremony" text NOT NULL,\n"setup_generation" text,\n"expires_at" bigint NOT NULL,\nPRIMARY KEY ("id")\n)'
					: "CREATE TABLE `auth_challenges` (\n`id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`challenge` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`ceremony` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`setup_generation` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`expires_at` bigint NOT NULL,\nPRIMARY KEY (`id`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"auth_challenges",
				engine === "pg"
					? [
							{ name: "id", type: "text", nullable: false },
							{ name: "challenge", type: "text", nullable: false },
							{ name: "ceremony", type: "text", nullable: false },
							{ name: "setup_generation", type: "text", nullable: true },
							{ name: "expires_at", type: "bigint", nullable: false },
						]
					: [
							{ name: "id", type: "varchar", nullable: false, length: 128 },
							{ name: "challenge", type: "longtext", nullable: false },
							{ name: "ceremony", type: "varchar", nullable: false, length: 128 },
							{ name: "setup_generation", type: "varchar", nullable: true, length: 128 },
							{ name: "expires_at", type: "bigint", nullable: false },
						],
				["id"],
				{ foreignKeys: [], checks: engine === "pg" ? [] : [] },
			),
		},
		{
			step: 4,
			name: "sessions",
			unique: [{ name: "sessions_hash_unique", columns: ["hash"] }],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "sessions" (\n"id" text NOT NULL,\n"hash" text NOT NULL,\n"created_at" bigint NOT NULL,\n"expires_at" bigint NOT NULL,\n"last_seen_at" bigint,\nPRIMARY KEY ("id")\n)'
					: "CREATE TABLE `sessions` (\n`id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`created_at` bigint NOT NULL,\n`expires_at` bigint NOT NULL,\n`last_seen_at` bigint,\nPRIMARY KEY (`id`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"sessions",
				engine === "pg"
					? [
							{ name: "id", type: "text", nullable: false },
							{ name: "hash", type: "text", nullable: false },
							{ name: "created_at", type: "bigint", nullable: false },
							{ name: "expires_at", type: "bigint", nullable: false },
							{ name: "last_seen_at", type: "bigint", nullable: true },
						]
					: [
							{ name: "id", type: "varchar", nullable: false, length: 128 },
							{ name: "hash", type: "varchar", nullable: false, length: 64 },
							{ name: "created_at", type: "bigint", nullable: false },
							{ name: "expires_at", type: "bigint", nullable: false },
							{ name: "last_seen_at", type: "bigint", nullable: true },
						],
				["id"],
				{ foreignKeys: [], checks: engine === "pg" ? [] : [] },
			),
		},
		{
			step: 7,
			name: "enrollments",
			unique: [{ name: "enrollments_family_unique", columns: ["family"] }],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "enrollments" (\n"id" text NOT NULL,\n"device_secret_hash" text NOT NULL,\n"user_code" text NOT NULL,\n"agent_name" text NOT NULL,\n"kind" text NOT NULL,\n"host" text NOT NULL,\n"status" text NOT NULL CHECK ("status" IN (\'pending\',\'approved\',\'denied\',\'collected\')),\n"family" text NOT NULL,\n"created_at" bigint NOT NULL,\n"expires_at" bigint NOT NULL,\n"collected_at" bigint,\n"scopes" text,\n"access_seconds" bigint,\n"refresh_seconds" bigint,\nPRIMARY KEY ("id")\n)'
					: "CREATE TABLE `enrollments` (\n`id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`device_secret_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`user_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`agent_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`kind` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`host` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL CHECK (`status` IN ('pending','approved','denied','collected')),\n`family` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`created_at` bigint NOT NULL,\n`expires_at` bigint NOT NULL,\n`collected_at` bigint,\n`scopes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`access_seconds` bigint,\n`refresh_seconds` bigint,\nPRIMARY KEY (`id`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"enrollments",
				engine === "pg"
					? [
							{ name: "id", type: "text", nullable: false },
							{ name: "device_secret_hash", type: "text", nullable: false },
							{ name: "user_code", type: "text", nullable: false },
							{ name: "agent_name", type: "text", nullable: false },
							{ name: "kind", type: "text", nullable: false },
							{ name: "host", type: "text", nullable: false },
							{ name: "status", type: "text", nullable: false },
							{ name: "family", type: "text", nullable: false },
							{ name: "created_at", type: "bigint", nullable: false },
							{ name: "expires_at", type: "bigint", nullable: false },
							{ name: "collected_at", type: "bigint", nullable: true },
							{ name: "scopes", type: "text", nullable: true },
							{ name: "access_seconds", type: "bigint", nullable: true },
							{ name: "refresh_seconds", type: "bigint", nullable: true },
						]
					: [
							{ name: "id", type: "varchar", nullable: false, length: 128 },
							{ name: "device_secret_hash", type: "varchar", nullable: false, length: 64 },
							{ name: "user_code", type: "varchar", nullable: false, length: 128 },
							{ name: "agent_name", type: "varchar", nullable: false, length: 64 },
							{ name: "kind", type: "longtext", nullable: false },
							{ name: "host", type: "longtext", nullable: false },
							{ name: "status", type: "varchar", nullable: false, length: 16 },
							{ name: "family", type: "varchar", nullable: false, length: 128 },
							{ name: "created_at", type: "bigint", nullable: false },
							{ name: "expires_at", type: "bigint", nullable: false },
							{ name: "collected_at", type: "bigint", nullable: true },
							{ name: "scopes", type: "longtext", nullable: true },
							{ name: "access_seconds", type: "bigint", nullable: true },
							{ name: "refresh_seconds", type: "bigint", nullable: true },
						],
				["id"],
				{
					foreignKeys: [],
					checks:
						engine === "pg"
							? ["(status = ANY (ARRAY['pending'::text, 'approved'::text, 'denied'::text, 'collected'::text]))"]
							: [
									"(`status` in (_utf8mb4\\'pending\\',_utf8mb4\\'approved\\',_utf8mb4\\'denied\\',_utf8mb4\\'collected\\'))",
								],
				},
			),
		},
		{
			step: 7,
			name: "tokens",
			unique: [{ name: "tokens_hash_unique", columns: ["hash"] }],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "tokens" (\n"id" text NOT NULL,\n"pair_id" text NOT NULL,\n"family" text NOT NULL,\n"agent" text NOT NULL,\n"kind" text NOT NULL CHECK ("kind" IN (\'access\',\'refresh\')),\n"hash" text NOT NULL,\n"label" text NOT NULL,\n"scopes" text NOT NULL,\n"expires_at" bigint NOT NULL,\n"created_at" bigint NOT NULL,\n"last_used_at" bigint,\n"revoked_at" bigint,\n"rotated_to" text,\n"rotated_at" bigint,\nPRIMARY KEY ("id")\n)'
					: "CREATE TABLE `tokens` (\n`id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`pair_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`family` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`agent` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`kind` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL CHECK (`kind` IN ('access','refresh')),\n`hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`label` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`scopes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`expires_at` bigint NOT NULL,\n`created_at` bigint NOT NULL,\n`last_used_at` bigint,\n`revoked_at` bigint,\n`rotated_to` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`rotated_at` bigint,\nPRIMARY KEY (`id`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"tokens",
				engine === "pg"
					? [
							{ name: "id", type: "text", nullable: false },
							{ name: "pair_id", type: "text", nullable: false },
							{ name: "family", type: "text", nullable: false },
							{ name: "agent", type: "text", nullable: false },
							{ name: "kind", type: "text", nullable: false },
							{ name: "hash", type: "text", nullable: false },
							{ name: "label", type: "text", nullable: false },
							{ name: "scopes", type: "text", nullable: false },
							{ name: "expires_at", type: "bigint", nullable: false },
							{ name: "created_at", type: "bigint", nullable: false },
							{ name: "last_used_at", type: "bigint", nullable: true },
							{ name: "revoked_at", type: "bigint", nullable: true },
							{ name: "rotated_to", type: "text", nullable: true },
							{ name: "rotated_at", type: "bigint", nullable: true },
						]
					: [
							{ name: "id", type: "varchar", nullable: false, length: 128 },
							{ name: "pair_id", type: "varchar", nullable: false, length: 128 },
							{ name: "family", type: "varchar", nullable: false, length: 128 },
							{ name: "agent", type: "varchar", nullable: false, length: 64 },
							{ name: "kind", type: "varchar", nullable: false, length: 16 },
							{ name: "hash", type: "varchar", nullable: false, length: 64 },
							{ name: "label", type: "longtext", nullable: false },
							{ name: "scopes", type: "longtext", nullable: false },
							{ name: "expires_at", type: "bigint", nullable: false },
							{ name: "created_at", type: "bigint", nullable: false },
							{ name: "last_used_at", type: "bigint", nullable: true },
							{ name: "revoked_at", type: "bigint", nullable: true },
							{ name: "rotated_to", type: "varchar", nullable: true, length: 128 },
							{ name: "rotated_at", type: "bigint", nullable: true },
						],
				["id"],
				{
					foreignKeys: [],
					checks:
						engine === "pg"
							? ["(kind = ANY (ARRAY['access'::text, 'refresh'::text]))"]
							: ["(`kind` in (_utf8mb4\\'access\\',_utf8mb4\\'refresh\\'))"],
				},
			),
		},
		{
			step: 8,
			name: "refresh_receipts",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "refresh_receipts" (\n"predecessor" text NOT NULL,\n"family" text NOT NULL,\n"successor_access_id" text NOT NULL,\n"successor_refresh_id" text NOT NULL,\n"expires_at" bigint NOT NULL,\n"salt" text NOT NULL,\n"nonce" text NOT NULL,\n"ciphertext" text NOT NULL,\n"tag" text NOT NULL,\nPRIMARY KEY ("predecessor")\n)'
					: "CREATE TABLE `refresh_receipts` (\n`predecessor` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`family` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`successor_access_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`successor_refresh_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`expires_at` bigint NOT NULL,\n`salt` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`nonce` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`ciphertext` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`tag` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\nPRIMARY KEY (`predecessor`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"refresh_receipts",
				engine === "pg"
					? [
							{ name: "predecessor", type: "text", nullable: false },
							{ name: "family", type: "text", nullable: false },
							{ name: "successor_access_id", type: "text", nullable: false },
							{ name: "successor_refresh_id", type: "text", nullable: false },
							{ name: "expires_at", type: "bigint", nullable: false },
							{ name: "salt", type: "text", nullable: false },
							{ name: "nonce", type: "text", nullable: false },
							{ name: "ciphertext", type: "text", nullable: false },
							{ name: "tag", type: "text", nullable: false },
						]
					: [
							{ name: "predecessor", type: "varchar", nullable: false, length: 128 },
							{ name: "family", type: "varchar", nullable: false, length: 128 },
							{ name: "successor_access_id", type: "varchar", nullable: false, length: 128 },
							{ name: "successor_refresh_id", type: "varchar", nullable: false, length: 128 },
							{ name: "expires_at", type: "bigint", nullable: false },
							{ name: "salt", type: "longtext", nullable: false },
							{ name: "nonce", type: "longtext", nullable: false },
							{ name: "ciphertext", type: "longtext", nullable: false },
							{ name: "tag", type: "longtext", nullable: false },
						],
				["predecessor"],
				{ foreignKeys: [], checks: engine === "pg" ? [] : [] },
			),
		},
		{
			step: 8,
			name: "refresh_idempotency",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "refresh_idempotency" (\n"family" text NOT NULL,\n"key_hash" text NOT NULL,\n"predecessor" text NOT NULL,\n"expires_at" bigint NOT NULL,\nPRIMARY KEY ("family","key_hash")\n)'
					: "CREATE TABLE `refresh_idempotency` (\n`family` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`key_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`predecessor` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`expires_at` bigint NOT NULL,\nPRIMARY KEY (`family`,`key_hash`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"refresh_idempotency",
				engine === "pg"
					? [
							{ name: "family", type: "text", nullable: false },
							{ name: "key_hash", type: "text", nullable: false },
							{ name: "predecessor", type: "text", nullable: false },
							{ name: "expires_at", type: "bigint", nullable: false },
						]
					: [
							{ name: "family", type: "varchar", nullable: false, length: 128 },
							{ name: "key_hash", type: "varchar", nullable: false, length: 64 },
							{ name: "predecessor", type: "varchar", nullable: false, length: 128 },
							{ name: "expires_at", type: "bigint", nullable: false },
						],
				["family", "key_hash"],
				{ foreignKeys: [], checks: engine === "pg" ? [] : [] },
			),
		},
		{
			step: 11,
			name: "mint_receipts",
			unique: [{ name: "mint_receipts_session_id_proof_hash_unique", columns: ["session_id", "proof_hash"] }],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "mint_receipts" (\n"session_id" text NOT NULL,\n"key_hash" text NOT NULL,\n"request_hash" text NOT NULL,\n"proof_hash" text NOT NULL,\n"family" text NOT NULL,\n"successor_access_id" text NOT NULL,\n"successor_refresh_id" text NOT NULL,\n"expires_at" bigint NOT NULL,\n"salt" text NOT NULL,\n"nonce" text NOT NULL,\n"ciphertext" text NOT NULL,\n"tag" text NOT NULL,\nPRIMARY KEY ("session_id","key_hash")\n)'
					: "CREATE TABLE `mint_receipts` (\n`session_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`key_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`request_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`proof_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`family` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`successor_access_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`successor_refresh_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`expires_at` bigint NOT NULL,\n`salt` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`nonce` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`ciphertext` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`tag` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\nPRIMARY KEY (`session_id`,`key_hash`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"mint_receipts",
				engine === "pg"
					? [
							{ name: "session_id", type: "text", nullable: false },
							{ name: "key_hash", type: "text", nullable: false },
							{ name: "request_hash", type: "text", nullable: false },
							{ name: "proof_hash", type: "text", nullable: false },
							{ name: "family", type: "text", nullable: false },
							{ name: "successor_access_id", type: "text", nullable: false },
							{ name: "successor_refresh_id", type: "text", nullable: false },
							{ name: "expires_at", type: "bigint", nullable: false },
							{ name: "salt", type: "text", nullable: false },
							{ name: "nonce", type: "text", nullable: false },
							{ name: "ciphertext", type: "text", nullable: false },
							{ name: "tag", type: "text", nullable: false },
						]
					: [
							{ name: "session_id", type: "varchar", nullable: false, length: 128 },
							{ name: "key_hash", type: "varchar", nullable: false, length: 64 },
							{ name: "request_hash", type: "varchar", nullable: false, length: 64 },
							{ name: "proof_hash", type: "varchar", nullable: false, length: 64 },
							{ name: "family", type: "varchar", nullable: false, length: 128 },
							{ name: "successor_access_id", type: "varchar", nullable: false, length: 128 },
							{ name: "successor_refresh_id", type: "varchar", nullable: false, length: 128 },
							{ name: "expires_at", type: "bigint", nullable: false },
							{ name: "salt", type: "longtext", nullable: false },
							{ name: "nonce", type: "longtext", nullable: false },
							{ name: "ciphertext", type: "longtext", nullable: false },
							{ name: "tag", type: "longtext", nullable: false },
						],
				["session_id", "key_hash"],
				{ foreignKeys: [], checks: engine === "pg" ? [] : [] },
			),
		},
	] as const;
