import { bootTableShape } from "./remote-boot-schema-shape.ts";
import type { SqlClient } from "effect/unstable/sql/SqlClient";

/** Explicit fresh remote schema; existing SQLite histories use boot-schema.ts. */
export const remoteBootRuntime = (sql: SqlClient, engine: "pg" | "mysql") =>
	[
		{
			step: 1,
			name: "generations",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "generations" (\n"n" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n"snapshot_dir" text,\n"entry_file" text NOT NULL,\n"status" text NOT NULL CHECK ("status" IN (\'starting\',\'live\',\'failed\',\'retired\')),\n"good" bigint NOT NULL DEFAULT 0 CHECK ("good" IN (0,1)),\n"stderr" text NOT NULL DEFAULT \'\',\n"error" text,\n"started_at" bigint NOT NULL,\n"healthy_at" bigint,\n"retired_at" bigint,\n"backup_id" text,\nPRIMARY KEY ("n")\n)'
					: "CREATE TABLE `generations` (\n`n` bigint AUTO_INCREMENT NOT NULL,\n`snapshot_dir` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`entry_file` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL CHECK (`status` IN ('starting','live','failed','retired')),\n`good` bigint NOT NULL DEFAULT 0 CHECK (`good` IN (0,1)),\n`stderr` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL DEFAULT (''),\n`error` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`started_at` bigint NOT NULL,\n`healthy_at` bigint,\n`retired_at` bigint,\n`backup_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\nPRIMARY KEY (`n`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"generations",
				engine === "pg"
					? [
							{ name: "n", type: "bigint", nullable: false, identity: true },
							{ name: "snapshot_dir", type: "text", nullable: true },
							{ name: "entry_file", type: "text", nullable: false },
							{ name: "status", type: "text", nullable: false },
							{ name: "good", type: "bigint", nullable: false, default: "0" },
							{ name: "stderr", type: "text", nullable: false, default: "''::text" },
							{ name: "error", type: "text", nullable: true },
							{ name: "started_at", type: "bigint", nullable: false },
							{ name: "healthy_at", type: "bigint", nullable: true },
							{ name: "retired_at", type: "bigint", nullable: true },
							{ name: "backup_id", type: "text", nullable: true },
						]
					: [
							{ name: "n", type: "bigint", nullable: false, identity: true },
							{ name: "snapshot_dir", type: "longtext", nullable: true },
							{ name: "entry_file", type: "longtext", nullable: false },
							{ name: "status", type: "varchar", nullable: false, length: 16 },
							{ name: "good", type: "bigint", nullable: false, default: "0" },
							{ name: "stderr", type: "longtext", nullable: false, default: "_utf8mb4\\'\\'" },
							{ name: "error", type: "longtext", nullable: true },
							{ name: "started_at", type: "bigint", nullable: false },
							{ name: "healthy_at", type: "bigint", nullable: true },
							{ name: "retired_at", type: "bigint", nullable: true },
							{ name: "backup_id", type: "varchar", nullable: true, length: 128 },
						],
				["n"],
				{
					foreignKeys: [],
					checks:
						engine === "pg"
							? [
									"(good = ANY (ARRAY[(0)::bigint, (1)::bigint]))",
									"(status = ANY (ARRAY['starting'::text, 'live'::text, 'failed'::text, 'retired'::text]))",
								]
							: [
									"(`status` in (_utf8mb4\\'starting\\',_utf8mb4\\'live\\',_utf8mb4\\'failed\\',_utf8mb4\\'retired\\'))",
									"(`good` in (0,1))",
								],
				},
			),
		},
		{
			step: 2,
			name: "settings",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "settings" (\n"key" text NOT NULL,\n"value" text NOT NULL,\nPRIMARY KEY ("key")\n)'
					: "CREATE TABLE `settings` (\n`key` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`value` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\nPRIMARY KEY (`key`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"settings",
				engine === "pg"
					? [
							{ name: "key", type: "text", nullable: false },
							{ name: "value", type: "text", nullable: false },
						]
					: [
							{ name: "key", type: "varchar", nullable: false, length: 128 },
							{ name: "value", type: "longtext", nullable: false },
						],
				["key"],
				{ foreignKeys: [], checks: engine === "pg" ? [] : [] },
			),
		},
		{
			step: 9,
			name: "child_attempts",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "child_attempts" (\n"id" text NOT NULL,\n"generation" bigint NOT NULL,\n"receipt" text NOT NULL,\n"opened" bigint NOT NULL DEFAULT 0,\n"closed" bigint NOT NULL DEFAULT 0,\n"boot_id" text,\nPRIMARY KEY ("id")\n)'
					: "CREATE TABLE `child_attempts` (\n`id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`generation` bigint NOT NULL,\n`receipt` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`opened` bigint NOT NULL DEFAULT 0,\n`closed` bigint NOT NULL DEFAULT 0,\n`boot_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\nPRIMARY KEY (`id`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"child_attempts",
				engine === "pg"
					? [
							{ name: "id", type: "text", nullable: false },
							{ name: "generation", type: "bigint", nullable: false },
							{ name: "receipt", type: "text", nullable: false },
							{ name: "opened", type: "bigint", nullable: false, default: "0" },
							{ name: "closed", type: "bigint", nullable: false, default: "0" },
							{ name: "boot_id", type: "text", nullable: true },
						]
					: [
							{ name: "id", type: "varchar", nullable: false, length: 128 },
							{ name: "generation", type: "bigint", nullable: false },
							{ name: "receipt", type: "longtext", nullable: false },
							{ name: "opened", type: "bigint", nullable: false, default: "0" },
							{ name: "closed", type: "bigint", nullable: false, default: "0" },
							{ name: "boot_id", type: "varchar", nullable: true, length: 128 },
						],
				["id"],
				{ foreignKeys: [], checks: engine === "pg" ? [] : [] },
			),
		},
		{
			step: 9,
			name: "backups",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "backups" (\n"id" text NOT NULL,\n"path" text NOT NULL,\n"reason" text NOT NULL,\n"bytes" bigint NOT NULL,\n"taken_at" bigint NOT NULL,\n"published_through" bigint,\n"generation" bigint,\n"legacy_store_id" text,\n"engine" text NOT NULL CHECK ("engine" IN (\'sqlite\',\'pg\',\'mysql\')),\nPRIMARY KEY ("id")\n)'
					: "CREATE TABLE `backups` (\n`id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`path` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`reason` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`bytes` bigint NOT NULL,\n`taken_at` bigint NOT NULL,\n`published_through` bigint,\n`generation` bigint,\n`legacy_store_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`engine` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL CHECK (`engine` IN ('sqlite','pg','mysql')),\nPRIMARY KEY (`id`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"backups",
				engine === "pg"
					? [
							{ name: "id", type: "text", nullable: false },
							{ name: "path", type: "text", nullable: false },
							{ name: "reason", type: "text", nullable: false },
							{ name: "bytes", type: "bigint", nullable: false },
							{ name: "taken_at", type: "bigint", nullable: false },
							{ name: "published_through", type: "bigint", nullable: true },
							{ name: "generation", type: "bigint", nullable: true },
							{ name: "legacy_store_id", type: "text", nullable: true },
							{ name: "engine", type: "text", nullable: false },
						]
					: [
							{ name: "id", type: "varchar", nullable: false, length: 128 },
							{ name: "path", type: "longtext", nullable: false },
							{ name: "reason", type: "longtext", nullable: false },
							{ name: "bytes", type: "bigint", nullable: false },
							{ name: "taken_at", type: "bigint", nullable: false },
							{ name: "published_through", type: "bigint", nullable: true },
							{ name: "generation", type: "bigint", nullable: true },
							{ name: "legacy_store_id", type: "varchar", nullable: true, length: 128 },
							{ name: "engine", type: "varchar", nullable: false, length: 16 },
						],
				["id"],
				{
					foreignKeys: [],
					checks:
						engine === "pg"
							? ["(engine = ANY (ARRAY['sqlite'::text, 'pg'::text, 'mysql'::text]))"]
							: ["(`engine` in (_utf8mb4\\'sqlite\\',_utf8mb4\\'pg\\',_utf8mb4\\'mysql\\'))"],
				},
			),
		},
		{
			step: 9,
			name: "cutover",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "cutover" (\n"singleton" bigint NOT NULL CHECK ("singleton"=1),\n"candidate" bigint NOT NULL,\n"prior" bigint,\n"backup" text,\n"lock_id" text NOT NULL,\n"family" text NOT NULL,\n"phase" text NOT NULL,\n"candidate_epoch" text,\nPRIMARY KEY ("singleton")\n)'
					: "CREATE TABLE `cutover` (\n`singleton` bigint NOT NULL CHECK (`singleton`=1),\n`candidate` bigint NOT NULL,\n`prior` bigint,\n`backup` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`lock_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`family` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`phase` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`candidate_epoch` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\nPRIMARY KEY (`singleton`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"cutover",
				engine === "pg"
					? [
							{ name: "singleton", type: "bigint", nullable: false },
							{ name: "candidate", type: "bigint", nullable: false },
							{ name: "prior", type: "bigint", nullable: true },
							{ name: "backup", type: "text", nullable: true },
							{ name: "lock_id", type: "text", nullable: false },
							{ name: "family", type: "text", nullable: false },
							{ name: "phase", type: "text", nullable: false },
							{ name: "candidate_epoch", type: "text", nullable: true },
						]
					: [
							{ name: "singleton", type: "bigint", nullable: false },
							{ name: "candidate", type: "bigint", nullable: false },
							{ name: "prior", type: "bigint", nullable: true },
							{ name: "backup", type: "varchar", nullable: true, length: 128 },
							{ name: "lock_id", type: "varchar", nullable: false, length: 128 },
							{ name: "family", type: "varchar", nullable: false, length: 128 },
							{ name: "phase", type: "varchar", nullable: false, length: 128 },
							{ name: "candidate_epoch", type: "varchar", nullable: true, length: 128 },
						],
				["singleton"],
				{ foreignKeys: [], checks: engine === "pg" ? ["(singleton = 1)"] : ["(`singleton` = 1)"] },
			),
		},
		{
			step: 13,
			name: "db_restore_requests",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "db_restore_requests" (\n"proof_id" text NOT NULL,\n"proof_hash" text NOT NULL,\n"session_id" text NOT NULL,\n"idempotency_key" text,\n"backup" text NOT NULL,\n"phase" text NOT NULL CHECK ("phase" IN (\'authorized\',\'restoring\',\'working\',\'rollback\',\'restored\',\'failed\')),\n"safety_backup" text,\n"generation" bigint,\n"restored_to_seq" bigint NOT NULL,\n"event_seq" bigint,\n"failure" text,\n"lock_id" text,\n"lock_family" text,\n"lock_owned" bigint NOT NULL DEFAULT 0 CHECK ("lock_owned" IN (0,1)),\n"candidate_epoch" text,\n"source_generation" bigint,\n"prior_generation" bigint,\n"source_batch" text,\n"active_guard" bigint GENERATED ALWAYS AS (CASE WHEN "phase" IN (\'authorized\',\'restoring\',\'working\',\'rollback\') THEN 1 ELSE NULL END) STORED,\nPRIMARY KEY ("proof_id")\n)'
					: "CREATE TABLE `db_restore_requests` (\n`proof_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`proof_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`session_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`idempotency_key` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`backup` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`phase` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL CHECK (`phase` IN ('authorized','restoring','working','rollback','restored','failed')),\n`safety_backup` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`generation` bigint,\n`restored_to_seq` bigint NOT NULL,\n`event_seq` bigint,\n`failure` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`lock_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`lock_family` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`lock_owned` bigint NOT NULL DEFAULT 0 CHECK (`lock_owned` IN (0,1)),\n`candidate_epoch` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`source_generation` bigint,\n`prior_generation` bigint,\n`source_batch` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`active_guard` bigint GENERATED ALWAYS AS (CASE WHEN `phase` IN ('authorized','restoring','working','rollback') THEN 1 ELSE NULL END) STORED,\nPRIMARY KEY (`proof_id`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"db_restore_requests",
				engine === "pg"
					? [
							{ name: "proof_id", type: "text", nullable: false },
							{ name: "proof_hash", type: "text", nullable: false },
							{ name: "session_id", type: "text", nullable: false },
							{ name: "idempotency_key", type: "text", nullable: true },
							{ name: "backup", type: "text", nullable: false },
							{ name: "phase", type: "text", nullable: false },
							{ name: "safety_backup", type: "text", nullable: true },
							{ name: "generation", type: "bigint", nullable: true },
							{ name: "restored_to_seq", type: "bigint", nullable: false },
							{ name: "event_seq", type: "bigint", nullable: true },
							{ name: "failure", type: "text", nullable: true },
							{ name: "lock_id", type: "text", nullable: true },
							{ name: "lock_family", type: "text", nullable: true },
							{ name: "lock_owned", type: "bigint", nullable: false, default: "0" },
							{ name: "candidate_epoch", type: "text", nullable: true },
							{ name: "source_generation", type: "bigint", nullable: true },
							{ name: "prior_generation", type: "bigint", nullable: true },
							{ name: "source_batch", type: "text", nullable: true },
							{
								name: "active_guard",
								type: "bigint",
								nullable: true,
								expression:
									"\nCASE\n    WHEN (phase = ANY (ARRAY['authorized'::text, 'restoring'::text, 'working'::text, 'rollback'::text])) THEN 1\n    ELSE NULL::integer\nEND",
							},
						]
					: [
							{ name: "proof_id", type: "varchar", nullable: false, length: 128 },
							{ name: "proof_hash", type: "varchar", nullable: false, length: 64 },
							{ name: "session_id", type: "varchar", nullable: false, length: 128 },
							{ name: "idempotency_key", type: "varchar", nullable: true, length: 200 },
							{ name: "backup", type: "varchar", nullable: false, length: 128 },
							{ name: "phase", type: "varchar", nullable: false, length: 16 },
							{ name: "safety_backup", type: "varchar", nullable: true, length: 128 },
							{ name: "generation", type: "bigint", nullable: true },
							{ name: "restored_to_seq", type: "bigint", nullable: false },
							{ name: "event_seq", type: "bigint", nullable: true },
							{ name: "failure", type: "longtext", nullable: true },
							{ name: "lock_id", type: "varchar", nullable: true, length: 128 },
							{ name: "lock_family", type: "varchar", nullable: true, length: 128 },
							{ name: "lock_owned", type: "bigint", nullable: false, default: "0" },
							{ name: "candidate_epoch", type: "varchar", nullable: true, length: 128 },
							{ name: "source_generation", type: "bigint", nullable: true },
							{ name: "prior_generation", type: "bigint", nullable: true },
							{ name: "source_batch", type: "varchar", nullable: true, length: 128 },
							{
								name: "active_guard",
								type: "bigint",
								nullable: true,
								expression:
									"(case when (`phase` in (_utf8mb4\\'authorized\\',_utf8mb4\\'restoring\\',_utf8mb4\\'working\\',_utf8mb4\\'rollback\\')) then 1 else NULL end)",
							},
						],
				["proof_id"],
				{
					foreignKeys: [],
					checks:
						engine === "pg"
							? [
									"(lock_owned = ANY (ARRAY[(0)::bigint, (1)::bigint]))",
									"(phase = ANY (ARRAY['authorized'::text, 'restoring'::text, 'working'::text, 'rollback'::text, 'restored'::text, 'failed'::text]))",
								]
							: [
									"(`phase` in (_utf8mb4\\'authorized\\',_utf8mb4\\'restoring\\',_utf8mb4\\'working\\',_utf8mb4\\'rollback\\',_utf8mb4\\'restored\\',_utf8mb4\\'failed\\'))",
									"(`lock_owned` in (0,1))",
								],
				},
			),
		},
		{
			step: 14,
			name: "public_paths",
			unique: [{ name: "public_paths_path_hash_unique", columns: ["path_hash"] }],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "public_paths" (\n"row_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n"path" text NOT NULL,\n"path_hash" text GENERATED ALWAYS AS (encode(sha256(decode(replace("path",chr(92),chr(92)||chr(92)),\'escape\')),\'hex\')) STORED,\nPRIMARY KEY ("row_id")\n)'
					: "CREATE TABLE `public_paths` (\n`row_id` bigint AUTO_INCREMENT NOT NULL,\n`path` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`path_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin GENERATED ALWAYS AS (SHA2(`path`,256)) STORED,\nPRIMARY KEY (`row_id`)\n) ENGINE=InnoDB",
			),
			postcondition: bootTableShape(
				sql,
				engine,
				"public_paths",
				engine === "pg"
					? [
							{ name: "row_id", type: "bigint", nullable: false, identity: true },
							{ name: "path", type: "text", nullable: false },
							{
								name: "path_hash",
								type: "text",
								nullable: true,
								expression:
									"encode(sha256(decode(replace(path, chr(92), (chr(92) || chr(92))), 'escape'::text)), 'hex'::text)",
							},
						]
					: [
							{ name: "row_id", type: "bigint", nullable: false, identity: true },
							{ name: "path", type: "longtext", nullable: false },
							{ name: "path_hash", type: "varchar", nullable: true, length: 64, expression: "sha2(`path`,256)" },
						],
				["row_id"],
				{ foreignKeys: [], checks: engine === "pg" ? [] : [] },
			),
		},
	] as const;
