import { tableShape } from "@comms/storage/remote-migrations";
import type { SqlClient } from "effect/unstable/sql/SqlClient";

/** Explicit fresh remote schema; existing SQLite histories use boot-schema.ts. */
export const remoteBootSource = (sql: SqlClient, engine: "pg" | "mysql") =>
	[
		{
			step: 3,
			name: "edit_lock",
			unique: [{ name: "edit_lock_id_unique", columns: ["id"] }],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "edit_lock" (\n"singleton" bigint NOT NULL CHECK ("singleton"=1),\n"id" text NOT NULL,\n"holder_family" text NOT NULL,\n"agent" text NOT NULL,\n"since" bigint NOT NULL,\n"expires" bigint NOT NULL,\n"ttl_seconds" bigint NOT NULL CHECK ("ttl_seconds" BETWEEN 1 AND 3600),\n"note" text NOT NULL,\n"cutover_in_flight" bigint NOT NULL DEFAULT 0 CHECK ("cutover_in_flight" IN (0,1)),\n"pending_release" text CHECK ("pending_release" IN (\'broken\',\'revoked\')),\n"reset_pin" bigint NOT NULL DEFAULT 0 CHECK ("reset_pin" IN (0,1,2)),\nPRIMARY KEY ("singleton")\n)'
					: "CREATE TABLE `edit_lock` (\n`singleton` bigint NOT NULL CHECK (`singleton`=1),\n`id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`holder_family` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`agent` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`since` bigint NOT NULL,\n`expires` bigint NOT NULL,\n`ttl_seconds` bigint NOT NULL CHECK (`ttl_seconds` BETWEEN 1 AND 3600),\n`note` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`cutover_in_flight` bigint NOT NULL DEFAULT 0 CHECK (`cutover_in_flight` IN (0,1)),\n`pending_release` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin CHECK (`pending_release` IN ('broken','revoked')),\n`reset_pin` bigint NOT NULL DEFAULT 0 CHECK (`reset_pin` IN (0,1,2)),\nPRIMARY KEY (`singleton`)\n)",
			),
			postcondition: tableShape(
				sql,
				"edit_lock",
				engine === "pg"
					? [
							{ name: "singleton", type: "bigint", nullable: false },
							{ name: "id", type: "text", nullable: false },
							{ name: "holder_family", type: "text", nullable: false },
							{ name: "agent", type: "text", nullable: false },
							{ name: "since", type: "bigint", nullable: false },
							{ name: "expires", type: "bigint", nullable: false },
							{ name: "ttl_seconds", type: "bigint", nullable: false },
							{ name: "note", type: "text", nullable: false },
							{ name: "cutover_in_flight", type: "bigint", nullable: false },
							{ name: "pending_release", type: "text", nullable: true },
							{ name: "reset_pin", type: "bigint", nullable: false },
						]
					: [
							{ name: "singleton", type: "bigint", nullable: false },
							{ name: "id", type: "varchar", nullable: false, length: 128 },
							{ name: "holder_family", type: "varchar", nullable: false, length: 128 },
							{ name: "agent", type: "varchar", nullable: false, length: 64 },
							{ name: "since", type: "bigint", nullable: false },
							{ name: "expires", type: "bigint", nullable: false },
							{ name: "ttl_seconds", type: "bigint", nullable: false },
							{ name: "note", type: "longtext", nullable: false },
							{ name: "cutover_in_flight", type: "bigint", nullable: false },
							{ name: "pending_release", type: "varchar", nullable: true, length: 16 },
							{ name: "reset_pin", type: "bigint", nullable: false },
						],
				["singleton"],
			),
		},
		{
			step: 3,
			name: "staging",
			unique: [{ name: "staging_lock_id_path_hash_unique", columns: ["lock_id", "path_hash"] }],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "staging" (\n"row_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n"lock_id" text NOT NULL,\n"path" text NOT NULL,\n"content" bytea,\n"sha" text,\n"at" bigint NOT NULL,\n"mode" bigint,\n"path_hash" text GENERATED ALWAYS AS (encode(sha256(decode(replace("path",chr(92),chr(92)||chr(92)),\'escape\')),\'hex\')) STORED,\nPRIMARY KEY ("row_id"),\nCHECK (("content" IS NULL)=("sha" IS NULL))\n)'
					: "CREATE TABLE `staging` (\n`row_id` bigint AUTO_INCREMENT NOT NULL,\n`lock_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`path` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`content` longblob,\n`sha` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`at` bigint NOT NULL,\n`mode` bigint,\n`path_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin GENERATED ALWAYS AS (SHA2(`path`,256)) STORED,\nPRIMARY KEY (`row_id`),\nCHECK ((`content` IS NULL)=(`sha` IS NULL))\n)",
			),
			postcondition: tableShape(
				sql,
				"staging",
				engine === "pg"
					? [
							{ name: "row_id", type: "bigint", nullable: false },
							{ name: "lock_id", type: "text", nullable: false },
							{ name: "path", type: "text", nullable: false },
							{ name: "content", type: "bytea", nullable: true },
							{ name: "sha", type: "text", nullable: true },
							{ name: "at", type: "bigint", nullable: false },
							{ name: "mode", type: "bigint", nullable: true },
							{
								name: "path_hash",
								type: "text",
								nullable: true,
								expression: "encode(sha256(decode(replace(\"path\",chr(92),chr(92)||chr(92)),'escape')),'hex')",
							},
						]
					: [
							{ name: "row_id", type: "bigint", nullable: false },
							{ name: "lock_id", type: "varchar", nullable: false, length: 128 },
							{ name: "path", type: "longtext", nullable: false },
							{ name: "content", type: "longblob", nullable: true },
							{ name: "sha", type: "varchar", nullable: true, length: 64 },
							{ name: "at", type: "bigint", nullable: false },
							{ name: "mode", type: "bigint", nullable: true },
							{ name: "path_hash", type: "varchar", nullable: true, length: 64, expression: "SHA2(`path`,256)" },
						],
				["row_id"],
			),
		},
		{
			step: 5,
			name: "source_batches",
			unique: [],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "source_batches" (\n"id" text NOT NULL,\n"lock_id" text,\n"agent" text NOT NULL,\n"at" bigint NOT NULL,\n"state" text NOT NULL CHECK ("state" IN (\'publishing\',\'published\')),\n"publishing_guard" bigint GENERATED ALWAYS AS (CASE WHEN "state"=\'publishing\' THEN 1 ELSE NULL END) STORED,\nPRIMARY KEY ("id")\n)'
					: "CREATE TABLE `source_batches` (\n`id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`lock_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`agent` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`at` bigint NOT NULL,\n`state` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL CHECK (`state` IN ('publishing','published')),\n`publishing_guard` bigint GENERATED ALWAYS AS (CASE WHEN `state`='publishing' THEN 1 ELSE NULL END) STORED,\nPRIMARY KEY (`id`)\n)",
			),
			postcondition: tableShape(
				sql,
				"source_batches",
				engine === "pg"
					? [
							{ name: "id", type: "text", nullable: false },
							{ name: "lock_id", type: "text", nullable: true },
							{ name: "agent", type: "text", nullable: false },
							{ name: "at", type: "bigint", nullable: false },
							{ name: "state", type: "text", nullable: false },
							{
								name: "publishing_guard",
								type: "bigint",
								nullable: true,
								expression: "CASE WHEN \"state\"='publishing' THEN 1 ELSE NULL END",
							},
						]
					: [
							{ name: "id", type: "varchar", nullable: false, length: 128 },
							{ name: "lock_id", type: "varchar", nullable: true, length: 128 },
							{ name: "agent", type: "varchar", nullable: false, length: 64 },
							{ name: "at", type: "bigint", nullable: false },
							{ name: "state", type: "varchar", nullable: false, length: 16 },
							{
								name: "publishing_guard",
								type: "bigint",
								nullable: true,
								expression: "CASE WHEN `state`='publishing' THEN 1 ELSE NULL END",
							},
						],
				["id"],
			),
		},
		{
			step: 5,
			name: "source_changes",
			unique: [{ name: "source_changes_batch_path_hash_unique", columns: ["batch", "path_hash"] }],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "source_changes" (\n"row_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n"batch" text NOT NULL,\n"path" text NOT NULL,\n"before" bytea,\n"before_sha" text,\n"before_mode" bigint,\n"desired" bytea,\n"desired_sha" text,\n"desired_mode" bigint,\n"before_directory" bigint NOT NULL DEFAULT 0 CHECK ("before_directory" IN (0,1)),\n"desired_directory" bigint NOT NULL DEFAULT 0 CHECK ("desired_directory" IN (0,1)),\n"path_hash" text GENERATED ALWAYS AS (encode(sha256(decode(replace("path",chr(92),chr(92)||chr(92)),\'escape\')),\'hex\')) STORED,\nPRIMARY KEY ("row_id"),\nFOREIGN KEY ("batch") REFERENCES "source_batches"("id"),\nCHECK (("before" IS NULL)=("before_sha" IS NULL)),\nCHECK (("before" IS NULL)=("before_mode" IS NULL)),\nCHECK (("desired" IS NULL)=("desired_sha" IS NULL)),\nCHECK (("desired" IS NULL)=("desired_mode" IS NULL))\n)'
					: "CREATE TABLE `source_changes` (\n`row_id` bigint AUTO_INCREMENT NOT NULL,\n`batch` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`path` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`before` longblob,\n`before_sha` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`before_mode` bigint,\n`desired` longblob,\n`desired_sha` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`desired_mode` bigint,\n`before_directory` bigint NOT NULL DEFAULT 0 CHECK (`before_directory` IN (0,1)),\n`desired_directory` bigint NOT NULL DEFAULT 0 CHECK (`desired_directory` IN (0,1)),\n`path_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin GENERATED ALWAYS AS (SHA2(`path`,256)) STORED,\nPRIMARY KEY (`row_id`),\nFOREIGN KEY (`batch`) REFERENCES `source_batches`(`id`),\nCHECK ((`before` IS NULL)=(`before_sha` IS NULL)),\nCHECK ((`before` IS NULL)=(`before_mode` IS NULL)),\nCHECK ((`desired` IS NULL)=(`desired_sha` IS NULL)),\nCHECK ((`desired` IS NULL)=(`desired_mode` IS NULL))\n)",
			),
			postcondition: tableShape(
				sql,
				"source_changes",
				engine === "pg"
					? [
							{ name: "row_id", type: "bigint", nullable: false },
							{ name: "batch", type: "text", nullable: false },
							{ name: "path", type: "text", nullable: false },
							{ name: "before", type: "bytea", nullable: true },
							{ name: "before_sha", type: "text", nullable: true },
							{ name: "before_mode", type: "bigint", nullable: true },
							{ name: "desired", type: "bytea", nullable: true },
							{ name: "desired_sha", type: "text", nullable: true },
							{ name: "desired_mode", type: "bigint", nullable: true },
							{ name: "before_directory", type: "bigint", nullable: false },
							{ name: "desired_directory", type: "bigint", nullable: false },
							{
								name: "path_hash",
								type: "text",
								nullable: true,
								expression: "encode(sha256(decode(replace(\"path\",chr(92),chr(92)||chr(92)),'escape')),'hex')",
							},
						]
					: [
							{ name: "row_id", type: "bigint", nullable: false },
							{ name: "batch", type: "varchar", nullable: false, length: 128 },
							{ name: "path", type: "longtext", nullable: false },
							{ name: "before", type: "longblob", nullable: true },
							{ name: "before_sha", type: "varchar", nullable: true, length: 64 },
							{ name: "before_mode", type: "bigint", nullable: true },
							{ name: "desired", type: "longblob", nullable: true },
							{ name: "desired_sha", type: "varchar", nullable: true, length: 64 },
							{ name: "desired_mode", type: "bigint", nullable: true },
							{ name: "before_directory", type: "bigint", nullable: false },
							{ name: "desired_directory", type: "bigint", nullable: false },
							{ name: "path_hash", type: "varchar", nullable: true, length: 64, expression: "SHA2(`path`,256)" },
						],
				["row_id"],
			),
		},
		{
			step: 5,
			name: "versions",
			unique: [{ name: "versions_batch_path_hash_unique", columns: ["batch", "path_hash"] }],
			run: sql.unsafe(
				engine === "pg"
					? 'CREATE TABLE "versions" (\n"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n"batch" text NOT NULL,\n"path" text NOT NULL,\n"agent" text NOT NULL,\n"at" bigint NOT NULL,\n"content" bytea,\n"sha" text,\n"mode" bigint,\n"previous_content" bytea,\n"previous_sha" text,\n"previous_mode" bigint,\n"versioned" bigint NOT NULL CHECK ("versioned" IN (0,1)),\n"reason" text CHECK ("reason"=\'size_limit\'),\n"previous_directory" bigint NOT NULL DEFAULT 0 CHECK ("previous_directory" IN (0,1)),\n"directory" bigint NOT NULL DEFAULT 0 CHECK ("directory" IN (0,1)),\n"path_hash" text GENERATED ALWAYS AS (encode(sha256(decode(replace("path",chr(92),chr(92)||chr(92)),\'escape\')),\'hex\')) STORED,\nPRIMARY KEY ("id"),\nFOREIGN KEY ("batch") REFERENCES "source_batches"("id")\n)'
					: "CREATE TABLE `versions` (\n`id` bigint AUTO_INCREMENT NOT NULL,\n`batch` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`path` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`agent` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,\n`at` bigint NOT NULL,\n`content` longblob,\n`sha` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`mode` bigint,\n`previous_content` longblob,\n`previous_sha` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin,\n`previous_mode` bigint,\n`versioned` bigint NOT NULL CHECK (`versioned` IN (0,1)),\n`reason` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin CHECK (`reason`='size_limit'),\n`previous_directory` bigint NOT NULL DEFAULT 0 CHECK (`previous_directory` IN (0,1)),\n`directory` bigint NOT NULL DEFAULT 0 CHECK (`directory` IN (0,1)),\n`path_hash` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin GENERATED ALWAYS AS (SHA2(`path`,256)) STORED,\nPRIMARY KEY (`id`),\nFOREIGN KEY (`batch`) REFERENCES `source_batches`(`id`)\n)",
			),
			postcondition: tableShape(
				sql,
				"versions",
				engine === "pg"
					? [
							{ name: "id", type: "bigint", nullable: false },
							{ name: "batch", type: "text", nullable: false },
							{ name: "path", type: "text", nullable: false },
							{ name: "agent", type: "text", nullable: false },
							{ name: "at", type: "bigint", nullable: false },
							{ name: "content", type: "bytea", nullable: true },
							{ name: "sha", type: "text", nullable: true },
							{ name: "mode", type: "bigint", nullable: true },
							{ name: "previous_content", type: "bytea", nullable: true },
							{ name: "previous_sha", type: "text", nullable: true },
							{ name: "previous_mode", type: "bigint", nullable: true },
							{ name: "versioned", type: "bigint", nullable: false },
							{ name: "reason", type: "text", nullable: true },
							{ name: "previous_directory", type: "bigint", nullable: false },
							{ name: "directory", type: "bigint", nullable: false },
							{
								name: "path_hash",
								type: "text",
								nullable: true,
								expression: "encode(sha256(decode(replace(\"path\",chr(92),chr(92)||chr(92)),'escape')),'hex')",
							},
						]
					: [
							{ name: "id", type: "bigint", nullable: false },
							{ name: "batch", type: "varchar", nullable: false, length: 128 },
							{ name: "path", type: "longtext", nullable: false },
							{ name: "agent", type: "varchar", nullable: false, length: 64 },
							{ name: "at", type: "bigint", nullable: false },
							{ name: "content", type: "longblob", nullable: true },
							{ name: "sha", type: "varchar", nullable: true, length: 64 },
							{ name: "mode", type: "bigint", nullable: true },
							{ name: "previous_content", type: "longblob", nullable: true },
							{ name: "previous_sha", type: "varchar", nullable: true, length: 64 },
							{ name: "previous_mode", type: "bigint", nullable: true },
							{ name: "versioned", type: "bigint", nullable: false },
							{ name: "reason", type: "varchar", nullable: true, length: 16 },
							{ name: "previous_directory", type: "bigint", nullable: false },
							{ name: "directory", type: "bigint", nullable: false },
							{ name: "path_hash", type: "varchar", nullable: true, length: 64, expression: "SHA2(`path`,256)" },
						],
				["id"],
			),
		},
	] as const;
