import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { Effect, Redacted, Schema } from "effect";
import { Reactivity } from "effect/unstable/reactivity";
import { open } from "../../src/remote-driver.ts";
import { remoteMigrate } from "../../src/remote-migrations.ts";
import { transferInventory } from "../../src/transfer-inventory.ts";

const config = process.env.COMMS_TRANSFER_TEST_CONFIG;
if (!config) throw Error("Missing disposable transfer fixture configuration");
const settings = Schema.decodeSync(
	Schema.fromJsonString(
		Schema.Struct({
			engine: Schema.Literals(["pg", "mysql"]),
			host: Schema.String,
			port: Schema.Int,
			database: Schema.String,
			username: Schema.String,
			password: Schema.String,
		}),
	),
)(await readFile(config, "utf8"));
if (!/^comms_transfer_[a-z0-9_]+$/.test(settings.database))
	throw Error("A dedicated empty comms_transfer_ database is required");
await Effect.runPromise(
	Effect.scoped(
		Effect.gen(function* () {
			const sql = yield* open(
				{ ...settings, password: Redacted.make(settings.password), tls: false },
				"transfer-catalog-fixture",
			);
			assert.equal((yield* transferInventory(sql)).tables.length, 0, "Fixture database must be empty");
			const pg = settings.engine === "pg";
			try {
				yield* remoteMigrate<never, never>(sql, "boot_migrations", [{ id: 1, name: "fixture", operations: [] }]);
				yield* sql`CREATE TABLE parent(a VARCHAR(40),b BIGINT,PRIMARY KEY(a,b))`;
				if (pg)
					yield* sql`CREATE TABLE custom(id BIGINT GENERATED BY DEFAULT AS IDENTITY,note VARCHAR(17),a VARCHAR(40),b BIGINT,payload BYTEA,derived TEXT GENERATED ALWAYS AS (note || '!') STORED,PRIMARY KEY(id) INCLUDE(note),FOREIGN KEY(a,b) REFERENCES parent(a,b))`;
				else
					yield* sql`CREATE TABLE custom(id BIGINT AUTO_INCREMENT PRIMARY KEY,note VARCHAR(17),a VARCHAR(40),b BIGINT,payload LONGBLOB,derived VARCHAR(18) GENERATED ALWAYS AS (CONCAT(note,'!')) STORED,FOREIGN KEY(a,b) REFERENCES parent(a,b))`;
				const inventory = yield* transferInventory(sql);
				assert.deepEqual(
					inventory.tables.map((table) => table.name),
					pg
						? ["boot_migrations", "custom", "parent"]
						: ["boot_migrations", "boot_migrations_intent", "custom", "parent"],
				);
				assert.equal(
					inventory.tables
						.find((table) => table.name === "boot_migrations")
						?.columns.find((column) => column.name === "created_at")?.kind,
					"unsupported",
				);
				const table = inventory.tables.find((table) => table.name === "custom");
				assert(table);
				assert.deepEqual(table.primaryKey, ["id"]);
				assert.equal(table.columns.find((column) => column.name === "id")?.identity, true);
				assert.equal(table.columns.find((column) => column.name === "note")?.length, 17);
				assert.equal(table.columns.find((column) => column.name === "payload")?.kind, "bytes");
				assert.equal(table.columns.find((column) => column.name === "derived")?.generated, true);
				assert.deepEqual(
					table.foreignKeys.map(({ columns, table, targets }) => ({ columns, table, targets })),
					[{ columns: ["a", "b"], table: "parent", targets: ["a", "b"] }],
				);
				yield* sql`CREATE VIEW extra_view AS SELECT id FROM custom`;
				assert.equal((yield* transferInventory(sql).pipe(Effect.result))._tag, "Failure");
				yield* sql`DROP VIEW extra_view`;
				if (pg) {
					yield* sql`CREATE TABLE inherited(extra TEXT) INHERITS(parent)`;
					assert.equal((yield* transferInventory(sql).pipe(Effect.result))._tag, "Failure");
					yield* sql`DROP TABLE inherited`;
					yield* sql`CREATE SCHEMA pgdata`;
					yield* sql`CREATE TABLE pgdata.hidden(value TEXT)`;
					assert.equal((yield* transferInventory(sql).pipe(Effect.result))._tag, "Failure");
					yield* sql`DROP TABLE pgdata.hidden`;
					yield* sql`DROP SCHEMA pgdata`;
					yield* sql`CREATE RULE suppress AS ON DELETE TO custom DO INSTEAD NOTHING`;
					assert.equal((yield* transferInventory(sql).pipe(Effect.result))._tag, "Failure");
					yield* sql`DROP RULE suppress ON custom`;
				} else {
					yield* sql`CREATE TABLE unsigned_value(value BIGINT UNSIGNED)`;
					assert.equal(
						(yield* transferInventory(sql)).tables.find((table) => table.name === "unsigned_value")?.columns[0]?.kind,
						"unsupported",
					);
					yield* sql`DROP TABLE unsigned_value`;
				}
				assert.deepEqual(yield* transferInventory(sql), inventory);
				process.stdout.write(`verified ${settings.engine} inventory\n`);
			} finally {
				// Only fixed fixture-owned objects in the explicitly empty disposable database.
				if (pg) {
					yield* sql`DROP RULE IF EXISTS suppress ON custom`.pipe(Effect.ignore);
					yield* sql`DROP TABLE IF EXISTS pgdata.hidden`.pipe(Effect.ignore);
					yield* sql`DROP SCHEMA IF EXISTS pgdata`.pipe(Effect.ignore);
					yield* sql`DROP TABLE IF EXISTS inherited`.pipe(Effect.ignore);
				} else yield* sql`DROP TABLE IF EXISTS unsigned_value`.pipe(Effect.ignore);
				yield* sql`DROP VIEW IF EXISTS extra_view`.pipe(Effect.ignore);
				yield* sql`DROP TABLE IF EXISTS custom`.pipe(Effect.ignore);
				yield* sql`DROP TABLE IF EXISTS parent`.pipe(Effect.ignore);
				yield* sql`DROP TABLE IF EXISTS boot_migrations_intent`.pipe(Effect.ignore);
				yield* sql`DROP TABLE IF EXISTS boot_migrations`.pipe(Effect.ignore);
			}
		}),
	).pipe(Effect.provide(Reactivity.layer)),
);
