import { layer as eventsLayer } from "../../src/events.ts";
import assert from "node:assert/strict";
import { BunRuntime, BunServices } from "@effect/platform-bun";
import * as SqliteClient from "@effect/sql-sqlite-bun/SqliteClient";
import { Console, DateTime, Effect, FileSystem, Layer, Schema } from "effect";
import { ChildProcessSpawner } from "effect/unstable/process";
import { SqlClient } from "effect/unstable/sql";
import { initializeBootSchema } from "../../src/boot-schema.ts";
import { EditAuthority, EditLock, EditRejected, layer as lockLayer } from "../../src/edit-lock.ts";
import { SourceFiles, layer as sourceLayer } from "../../src/source-files.ts";
import { SourceRejected } from "../../src/source-schema.ts";

const main = Effect.gen(function* () {
	const root = process.argv[2];
	if (!root) return yield* Effect.die("Missing root");
	const scenario = yield* Schema.decodeUnknownEffect(
		Schema.Literals(["authority", "remove-before", "file-before", "remove-after", "file-after"]),
	)(process.argv[3]);
	const fs = yield* FileSystem.FileSystem;
	const spawner = yield* ChildProcessSpawner.ChildProcessSpawner;
	for (const directory of ["app/ext/custom", "selected", "pages"])
		yield* fs.makeDirectory(`${root}/${directory}`, { recursive: true });
	yield* fs.writeFileString(`${root}/app/main.ts`, "current");
	yield* fs.writeFileString(`${root}/app/ext/custom/index.ts`, "custom source");
	yield* fs.writeFileString(`${root}/selected/main.ts`, "seed");
	yield* fs.writeFileString(`${root}/pages/index.md`, "preserved page");
	if (scenario.startsWith("file")) {
		yield* fs.makeDirectory(`${root}/selected/ext`);
		yield* fs.writeFileString(`${root}/selected/ext/custom`, "replacement file");
	}
	const generated = Effect.gen(function* () {
		yield* fs.makeDirectory(`${root}/app/ext/custom/node_modules`, { recursive: true });
		yield* fs.writeFileString(`${root}/app/ext/custom/node_modules/keep`, "generated bytes");
	});
	if (scenario.endsWith("before")) yield* generated;
	yield* Effect.gen(function* () {
		yield* initializeBootSchema;
		const sql = yield* SqlClient.SqlClient;
		const now = (yield* DateTime.nowAsDate).getTime();
		yield* sql`INSERT INTO sessions(id,hash,created_at,expires_at) VALUES('reset-human','reset-session',${now},${now + 60000})`;
		let expireOnSample = false;
		let expirations = 0;
		const sampled = ChildProcessSpawner.make((command) =>
			Effect.gen(function* () {
				if (expireOnSample) {
					expireOnSample = false;
					expirations++;
					// checkChanges samples space after pinned() checked authority, before journal admission.
					yield* sql`UPDATE sessions SET expires_at=0 WHERE id='reset-human'`.pipe(Effect.orDie);
				}
				return yield* spawner.spawn(command);
			}),
		);
		yield* Effect.gen(function* () {
			const files = yield* SourceFiles;
			const lock = yield* EditLock;
			const held = (yield* lock.acquire("other", "other-agent")).value;
			const owner = { id: held.id, family: held.holder_family };
			yield* files.stage(owner, "app/main.ts", new TextEncoder().encode("borrowed staging"));
			const staged = (yield* lock.overlay(owner)).value;
			yield* lock.pin(owner, 1);
			const proposal = yield* files.prepareTrustedTree(owner, `${root}/selected`, "reset-human").pipe(Effect.result);
			if (scenario.endsWith("before")) {
				assert.ok(proposal._tag === "Failure");
				assert.ok(Schema.is(SourceRejected)(proposal.failure));
				assert.equal(proposal.failure.code, "external_conflict");
				assert.equal(proposal.failure.path, "app/ext/custom/node_modules");
			} else {
				assert.ok(proposal._tag === "Success");
				if (scenario.endsWith("after")) yield* generated;
				expireOnSample = scenario === "authority";
				const rejected = yield* files
					.publish(proposal.success)
					.pipe(
						Effect.provideService(EditAuthority, { kind: "human", id: "reset-human", expiresAt: now + 60000 }),
						Effect.result,
					);
				assert.ok(rejected._tag === "Failure");
				if (scenario === "authority") {
					assert.equal(expirations, 1);
					assert.ok(Schema.is(EditRejected)(rejected.failure));
					assert.equal(rejected.failure.code, "authority_expired");
				} else {
					assert.ok(Schema.is(SourceRejected)(rejected.failure));
					assert.equal(rejected.failure.code, "external_conflict");
					assert.equal(rejected.failure.path, "app/ext/custom/node_modules");
				}
				yield* files.discard(proposal.success);
			}
			assert.deepEqual(yield* sql`SELECT * FROM source_batches`, []);
			assert.deepEqual(yield* sql`SELECT * FROM source_changes`, []);
			assert.deepEqual(yield* sql`SELECT * FROM versions`, []);
			assert.equal(yield* fs.readFileString(`${root}/app/main.ts`), "current");
			assert.equal(yield* fs.readFileString(`${root}/app/ext/custom/index.ts`), "custom source");
			assert.equal(yield* fs.readFileString(`${root}/pages/index.md`), "preserved page");
			if (scenario !== "authority")
				assert.equal(yield* fs.readFileString(`${root}/app/ext/custom/node_modules/keep`), "generated bytes");
			assert.deepEqual((yield* lock.overlay(owner)).value, staged);
			yield* lock.finish(owner, { succeeded: false });
			assert.deepEqual((yield* lock.overlay(owner)).value, staged);
		}).pipe(
			Effect.provide(
				sourceLayer(root).pipe(Layer.provideMerge(lockLayer.pipe(Layer.provideMerge(eventsLayer(Effect.void))))),
			),
			Effect.provideService(ChildProcessSpawner.ChildProcessSpawner, sampled),
		);
	}).pipe(Effect.provide(SqliteClient.layer({ filename: `${root}/boot.db` })));
	yield* Console.log(`source reset boundary ${scenario} passed`);
}).pipe(Effect.scoped, Effect.provide(BunServices.layer));
main.pipe(BunRuntime.runMain);
